version: '3.8'

services:
  client:
    build:
      context: client/
      target: development
      dockerfile: Dockerfile
    environment:
      - PORT=5173
      - VITE_BACKEND_URL=http://localhost:8000
    command: bash -c "yarn && yarn dev"
    ports:
      - 5173:5173
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  server:
    build:
      context: server/
      target: development
      dockerfile: Dockerfile
    links:
      - db
    environment:
      - DB_NAME=db
      - DB_USER=dev
      - DB_PASSWORD=test
      - DB_PORT=5432
      - DB_HOST=localhost
      - DATABASE_URL=postgres://dev:test@0.0.0.0:5432/db
    ports:
      - 8080:8080
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/target
      - /usr/src/app/target/release
      - /usr/local/cargo
    restart: unless-stopped
  db:
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/database
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=db
volumes:
  client:
  server:
  pgdata:
