version: '3.8'

services:
  client:
    build:
      context: client/
      target: development
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - VITE_BACKEND_URL=http://localhost:8000
    command: bash -c "yarn && yarn dev"
    ports:
      - 5000:5000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  server:
    build:
      context: server/
      target: development
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_NAME=test-db
      - DB_USER=dev
      - DB_PASSWORD=test
      - DB_PORT=5432
      - DB_HOST=db
    ports:
      - 3000:3000
    volumes:
      - ./server:/usr/local/bin
      - /usr/local/bin
    restart: unless-stopped
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=test-db
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/database
volumes:
  client:
  server:
  db:
    driver: local
