# generic lite rust container with musl & openssl
FROM --platform=linux/amd64 rust:alpine3.17 as rust-alpine
RUN apk add --no-cache musl-dev openssl-dev
WORKDIR /usr/src/app

# generic chef to minimize redundancy
FROM rust-alpine as chef
RUN cargo install cargo-chef
RUN cargo install cargo-watch

# generate a recipe file for dependencies
FROM chef as planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

# build & cache dependencies
FROM chef as cacher
COPY --from=planner /usr/src/app/recipe.json recipe.json
RUN cargo chef cook --release --target x86_64-unknown-linux-musl --recipe-path recipe.json

# use rust:alpine3.17 docker image as builder
FROM rust-alpine as runtime
# copy build image
COPY . .
COPY --from=cacher /usr/src/app/target target
COPY --from=cacher /usr/local/cargo /usr/local/cargo
RUN cargo build
